version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-flask-to-do-list-web
    volumes:
      - ".:/app"
    env_file:
      - .env.dev
    ports:
      - "4001:4000"
    tty: true