apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-07-14T00:38:38Z"
  generation: 1
  labels:
    app: python-flask-to-do-list-web
  name: python-flask-to-do-list-web
  namespace: default
  resourceVersion: "4688"
  uid: c836b96b-48c7-474e-9dcc-c365d1a92c26
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-flask-to-do-list-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-flask-to-do-list-web
    spec:
      containers:
      - image: caprilespe/python-flask-to-do-list-web:v1
        imagePullPolicy: IfNotPresent
        name: python-flask-to-do-list-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-07-14T00:38:47Z"
    lastUpdateTime: "2023-07-14T00:38:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-07-14T00:38:38Z"
    lastUpdateTime: "2023-07-14T00:38:47Z"
    message: ReplicaSet "python-flask-to-do-list-web-57649b7698" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
