apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-07-14T00:41:40Z"
  labels:
    app: python-flask-to-do-list-web
  name: python-flask-to-do-list-web
  namespace: default
  resourceVersion: "4823"
  uid: 43be8029-4d32-476b-939b-6c5dbffe7628
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.233.71
  clusterIPs:
  - 10.104.233.71
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32457
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: python-flask-to-do-list-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
